"""Finance Deposit screenshot-review UI."""


def register_deposit_screenshot_ui(app):
    if getattr(app, "_titan_deposit_screenshot_ui_registered", False):
        return
    app._titan_deposit_screenshot_ui_registered = True

    from flask import Response

    @app.route("/api/deposit_professional/screenshot_ui", methods=["GET"])
    def deposit_professional_screenshot_ui():
        return Response(UI_HTML, mimetype="text/html")


UI_HTML = r'''<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Deposit Review</title><style>
*{box-sizing:border-box}body{margin:0;background:#07111f;color:#eef6ff;font-family:Inter,Arial,sans-serif;padding:12px}.top{display:flex;justify-content:space-between;gap:8px;align-items:center;margin-bottom:10px}.title{font-weight:900}.muted{color:#91afd1;font-size:11px}.grid{display:grid;grid-template-columns:1fr;gap:10px}.card{background:#101d2f;border:1px solid #243e5f;border-radius:16px;padding:12px}.row{display:grid;grid-template-columns:1fr 1fr;gap:8px}.pill{display:inline-block;border-radius:999px;background:#263b59;color:#bfdbfe;padding:5px 8px;font-size:10px;font-weight:900}input,textarea,select{width:100%;background:#07111f;border:1px solid #243e5f;border-radius:12px;color:#eef6ff;padding:10px;font-size:12px;margin-top:6px}button{border:0;border-radius:12px;padding:10px 11px;font-weight:900;color:#fff;background:#2aabee;margin-top:8px}.ok{background:#00C26F;color:#062013}.danger{background:#ff5d5d}.soft{background:#263b59}.proof{width:100%;max-height:360px;object-fit:contain;background:#020617;border:1px solid #243e5f;border-radius:12px;margin-top:8px}.risk{font-size:10px;color:#fbbf24;margin-top:5px}.btns{display:flex;gap:7px;flex-wrap:wrap}.empty{padding:20px;text-align:center;color:#91afd1}.stat{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin-bottom:10px}.stat div{background:#0b1727;border:1px solid #243e5f;border-radius:12px;padding:9px}.stat b{display:block;font-size:16px}
</style></head><body><div class="top"><div><div class="title">💰 Deposit Review</div><div class="muted">Screenshot-only payment proofs · admin approval required</div></div><button class="soft" onclick="load()">Refresh</button></div><div id="stat" class="stat"></div><div id="msg" class="muted"></div><div id="list" class="grid"></div><script>
const API='/api/deposit_professional';
function esc(v){return String(v??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]||c))}
function h(){const o={'Content-Type':'application/json'};try{const t=localStorage.getItem('TITAN_ADMIN_TOKEN')||'';if(t)o['X-Titan-Admin-Token']=t}catch(e){}return o}
async function j(url,opt={}){opt.headers=Object.assign(h(),opt.headers||{});const r=await fetch(url,opt);const d=await r.json().catch(()=>({status:'error',message:'Invalid JSON'}));if(!r.ok||d.status==='error')throw new Error(d.message||('HTTP '+r.status));return d}
function msg(t){document.getElementById('msg').textContent=t||''}
function wanted(d){const s=String(d.status||'').toLowerCase();return ['needs_admin_review','duplicate_review','payment_submitted','under_verification','approved','rejected'].includes(s)||d.screenshotOnly||d.source==='whatsapp_screenshot_only'}
function stats(all){let pending=0, approved=0, rejected=0;for(const d of all){const s=String(d.status||'').toLowerCase();if(['needs_admin_review','duplicate_review','payment_submitted','under_verification'].includes(s))pending++;else if(s==='approved')approved++;else if(s==='rejected')rejected++;}document.getElementById('stat').innerHTML=`<div><span class="muted">Pending</span><b>${pending}</b></div><div><span class="muted">Approved</span><b>${approved}</b></div><div><span class="muted">Rejected</span><b>${rejected}</b></div>`}
function card(d){const id=d.depositId||d.id||'';const risk=d.risk||{};const reasons=Array.isArray(risk.reasons)?risk.reasons.join(', '):'';const proof=d.proofUrl||d.screenshotUrl||'';const st=String(d.status||'');return `<div class="card" data-id="${esc(id)}"><div style="display:flex;justify-content:space-between;gap:8px"><div><b>${esc(d.customerName||d.phoneNumber||d.userId||'User')}</b><div class="muted">${esc(d.phoneNumber||d.userId||'')} · ${esc(id)}</div></div><span class="pill">${esc(st)}</span></div>${proof?`<a href="${esc(proof)}" target="_blank"><img class="proof" src="${esc(proof)}"></a>`:'<div class="empty">No screenshot preview</div>'}<div class="risk">Risk: ${esc(risk.level||'manual')} ${reasons?`· ${esc(reasons)}`:''}</div><div class="row"><div><div class="muted">Amount</div><input class="amt" type="number" value="${Number(d.amount||0)||''}" placeholder="Amount from bank/app"></div><div><div class="muted">UTR / Transaction ID</div><input class="utr" value="${esc(d.utr||'')}" placeholder="UTR required"></div></div><textarea class="note" placeholder="Admin note / reject reason">${esc(d.adminNote||'')}</textarea><div class="btns"><button class="soft save">Save Details</button><button class="ok approve">Approve + Credit</button><button class="danger reject">Reject</button></div></div>`}
async function saveDetails(box){const id=box.dataset.id;const amount=Number(box.querySelector('.amt').value||0);const utr=box.querySelector('.utr').value.trim();const adminNote=box.querySelector('.note').value.trim();return await j(API+'/screenshot_review',{method:'POST',body:JSON.stringify({depositId:id,amount,utr,adminNote,updatedBy:'finance_deposit_review'})})}
async function load(){try{msg('Loading...');const r=await j(API+'/list?limit=120');const all=(r.deposits||[]).filter(wanted);stats(all);document.getElementById('list').innerHTML=all.length?all.map(card).join(''):'<div class="empty">No deposit screenshots.</div>';msg('Loaded ✅')}catch(e){msg('Load failed: '+e.message)}}
document.addEventListener('click',async ev=>{const box=ev.target.closest('.card');if(!box)return;try{if(ev.target.classList.contains('save')){await saveDetails(box);msg('Saved ✅');load()}if(ev.target.classList.contains('approve')){await saveDetails(box);const id=box.dataset.id;await j(API+'/action',{method:'POST',body:JSON.stringify({depositId:id,action:'approve',force:true,updatedBy:'finance_deposit_review'})});msg('Approved + wallet credit done ✅');load()}if(ev.target.classList.contains('reject')){const id=box.dataset.id;const reason=box.querySelector('.note').value.trim()||prompt('Reject reason?','Payment not found / screenshot mismatch')||'';await j(API+'/action',{method:'POST',body:JSON.stringify({depositId:id,action:'reject',force:true,rejectReason:reason,updatedBy:'finance_deposit_review'})});msg('Rejected ✅');load()}}catch(e){msg('Action failed: '+e.message)}});
load();setInterval(load,10000);
</script></body></html>'''
